name: fundamento1
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pygame
  - sympy
  - tinydb
  - python-dotenv
  - requests
  - beautifulsoup4
  - unidecode
  - httpx
  - regex
  - aiohttp
  - cchardet
  - brotlipy
  - tqdm
  - easyocr
  - pymupdf
  - docling
  - pdfminer
  - camelot-py
  - tabula-py
  - pytesseract 
  - xhtml2pdf
  - matplotlib
  - r-turtlegraphics
  - pip:
    - layoutparser
    - ocrmypdf
    - pymupdf4llm